.eslintrc.json, .github/workflows/ci.yml, package-lock.json, package.json
Addresses issue #17.
Adds ESLint relevant packages for dependencies and initializes configuration file where custom rules for linting can be added.
Setup linting in CI.
`package.json` updated.
`npm run lint` scans all .ts & .js files for syntax errors and fixes them if possible.
=> Setup code linting

prisma/migrations/20220614182831_split_course_and_teaching_preference_model/migration.sql, prisma/schema.prisma
- Added new columns to the teaching preferences 
- Split up teaching preferences from courses preferences
=> Split up teaching pref from course pref

src/resolvers/index.ts
This should able to give a response while querying in Apollo Studio
=>  Query Resolvers

.github/workflows/ci.yml
Adds steps to workflow to build and publish docker image of backend application on main builds. Will be used for integration testing.
=> Updated workflow file to publish backend docker image to registry

src/resolvers/index.ts
This reverts commit 18560007875feca34c49fb22d6fc2ad1b9b8272b.
There were some linting and logic problems with it. Not ready for merge.
=> Revert " Query Resolvers (#53)"

.github/workflows/docker.yml, .github/workflows/e2e.yml, src/index.ts
This PR adds the shared tests as E2E tests which run alongside the existing test suite specific for backend.
How the E2E tests work is as follows:
1. The shared tests are imported into the pipeline (from main).
2. The other services (algo 1 and 2) are instantiated as service containers.
3. The backend is built and started in the background.
4. The shared test suite is started pointed to the service containers and backend.
A healthcheck endpoint is added as well as `/healthcheck`. 
The Docker build and push pipeline is fixed by adding the env var.
=> feat: E2E testing with backend

.env, .github/workflows/docker.yml, Procfile, README.md, package.json, prisma/seed.ts
This PR adds several improvements to the local development workflow.
* Configures `npm run setup` to run all the stages to get started with development.
* Includes a default `.env` for local development.
* Creates a user for both role types now.
=> feat: Local development improvements and fix Docker pipeline

data/historical-data-2019.json, package-lock.json, package.json, prisma/migrations/20220619060323_added_unique_tags/migration.sql, prisma/migrations/20220619063241_added_section_number_to_course_section/migration.sql, prisma/migrations/20220619063714_changed_section_number_to_string_from_int/migration.sql, prisma/migrations/20220620234510_added_course_title_and_user_display_name/migration.sql, prisma/migrations/20220622222511_made_display_name_optional/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/utils/index.ts, src/utils/seedingFunctions.ts, src/utils/time.ts, tsconfig.json
- Added historical data JSON file
- Updated Prisma schema
1. Added display name to User
2. Added title to Course
3. Removed meetingTime id from CourseSection
4. Added courseSection id to MeetingTime
5. Added Unique tags to a few of the model's combined fields
- Added some utility functions to be used in seeding
- Added seeding function
=> Seed database with historical data

package-lock.json, package.json
- Moved date-fns and date-fns-tz packages from a dev dependency to a regular dependency.
=> Move date-fns and date-fns-tz to be a regular dependency

src/prisma/schedule.ts, src/resolvers/resolverUtils.ts
This PR fixes the schedule by returning it in the shape in GraphQL schema expects and queries according to the description of the resolver in the GraphQL schema.
=> fix: Schedule resolver

Procfile
Adds Heroku Procfile which includes a release stage to run the migrations from Prisma
=> feat: add Procfile with migration command

src/prisma/user.ts, src/resolvers/index.ts, src/resolvers/resolverUtils.ts, src/schema/graphql.ts, src/schema/schema.graphql
Have added changes for GenerateScheduleInput:
- Added Term
- Added Course (Not sure the type of this)
Have added changes for User:
- Added hasPeng (to match prisma)
Have added some changes required by front end:
**High Priority Changes:**
- Added EditCourse Mutation
- Added Section Number
- Added Non-teaching term
- Added Teaching capacity
- Added Has Relief
- Added Relief Explanation
- Added Has topic
- Added Topic Description
- Added Display Name
**Low Priority Changes:**
- Added Course Title
- Added Query to grab all course preferences
- Query for all users
=> Updating Schema

data/teacher-pref-data.json, prisma/seed.ts, src/utils/index.ts, src/utils/seedingFunctions.ts
-Added teaching preference and course preference seeding
=> Add teaching pref seeding

src/client/algorithm1/api.ts, src/prisma/course.ts
-Updated the api typedef to reflect what is being returned by alg1
-Changed typedef of Course to have a single Professor object instead of an array of professor objects
-Added profs when upserting courses
=> Add profs to course upsert

prisma/seed.ts, src/prisma/course.ts, src/resolvers/index.ts, src/resolvers/resolverUtils.ts
Small changes to improve error handling in generate schedule and also a fix for the crashes that were happening when generating a schedule. 
When we received a 'TBD' as a prof for a course from algorithm it would crash as there are no profs with that name. 
A simple solution is to add a disabled 'TBD' user to fill in.
There are still some bugs with generate schedule after this one but they don't cause crashes.
=> Generate schedule crash fixes

src/auth/index.ts
- refactor hashing func to use async variants
- rename some constants
- add type to response objects
=> feat: add fill displayname from username

src/index.ts, src/resolvers/index.ts, src/resolvers/resolverUtils.ts
This PR refactors some code to allow the `message` field in `generateSchedule` mutation response to return the inputs used to call each algorithm to help with debugging efforts.
Algo 1 failing
```
{
"data": {
"generateSchedule": {
"success": false,
"message": "{\"message\":\"ALGORITHM1_COMPANY3: API call error: Bad Response:connect ECONNREFUSED 127.0.0.1:8080:undefined\",\"algorithm2\":{\"request\":[{\"subject\":\"CSC\",\"code\":\"111\",\"seng_ratio\":0.75,\"semester\":\"FALL\",\"capacity\":0}],\"response\":[{\"capacity\":331,\"code\":\"111\",\"semester\":\"FALL\",\"seng_ratio\":0.75,\"subject\":\"CSC\"}]},\"algorithm1\":{\"request\":{\"coursesToSchedule\":{\"fallCourses\":[{\"subject\":\"CSC\",\"courseNumber\":\"111\",\"numSections\":0,\"courseCapacity\":331,\"courseTitle\":\"Untitled(New …
```
=> feat: Return inputs used to call algos in error response of generateSchedule mutation

package.json, tsconfig.json
Small QOL improvement for debugging stuff
=> chore: enable source maps

src/prisma/user.ts, src/resolvers/index.ts, src/resolvers/resolverUtils.ts, src/utils/index.ts
This PR implements a followup from #122 where this PR will submit the saved prefs to algorithm 1.
In addition, this PR implements passing default pref values in the case a user has not filled out the survey. This default preference can be loaded in via environment variable `DEFAULT_PREF`.
=> feat: Pass semester prefs to algorithm 1

.github/workflows/db.yml
Fixes typo on db reset step and adds the force option for Prisma CLI.
=> fix: step name and force option

src/prisma/course.ts, src/resolvers/resolverUtils.ts
This adds profs to the courses query
=> Adding Profs to getCourses

prisma/schema.prisma, src/algorithm/index.ts, src/prisma/schedule.ts, src/resolvers/index.ts, src/resolvers/resolverUtils.ts, src/utils/time.ts
This PR implements validation for manual schedule editing for Company 3 when `skipValidation` is false
=> Validate schedule

data/base_courses.json
Adds courses and replaces CSC349 with CSC349A
=> fix: replace CSC349 with CSC349A

src/prisma/course.ts, src/resolvers/resolverUtils.ts
Had issues with generate schedule and unique constants failing. This only allows connecting with existing courses.
=> feat: remove upsert from generate schedule

src/resolvers/resolverUtils.ts
For each is converted to normal for loop
=> Fix Catching Non Existing Course Error
